[build]
  base = "/"
  publish = "public"  # 정적 파일들이 있는 경우
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "netlify/functions"